import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "../components/SessionWrapper";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Poppins } from 'next/font/google';
import AOSInit from "@/components/AOSInit";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="font-poppins bg-white text-black">
        <AOSInit />
        <SessionWrapper>
          <NavBar />
          {children}
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
